[custom]

ruleset=广告,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=广告,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=Google Bard,https://raw.githubusercontent.com/XiaoMengXinX/Clash_Rules/master/bard.list
ruleset=Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=GoogleCN,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list
ruleset=GooglePlay,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTubeMusic.list
ruleset=Spotify,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Spotify.list
ruleset=ChatGPT,https://raw.githubusercontent.com/XiaoMengXinX/Clash_Rules/master/OpenAI.list
ruleset=Bing,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.list
ruleset=OneDrive,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=Adobe,https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Adobe.list
ruleset=Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=Epic,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=Sony,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=Steam,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=HoYoGames,https://raw.githubusercontent.com/XiaoMengXinX/Clash_Rules/master/HoYoGames.list
ruleset=HoYoGamesUDP,https://raw.githubusercontent.com/XiaoMengXinX/Clash_Rules/master/HoYoGamesUDP.list
ruleset=Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=哔哩哔哩港澳台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=GFWList,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=直连,[]GEOIP,CN
ruleset=漏网之鱼,[]FINAL

custom_proxy_group=节点选择`select`[]故障转移`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]DIRECT

custom_proxy_group=手动选择1`select`.*`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]DIRECT
custom_proxy_group=手动选择2`select`.*`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]DIRECT
custom_proxy_group=手动选择3`select`.*`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]DIRECT
custom_proxy_group=手动选择4`select`.*`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]DIRECT

custom_proxy_group=FCM`select`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]直连
custom_proxy_group=Google Bard`select`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]直连
custom_proxy_group=Google`select`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]直连
custom_proxy_group=GoogleCN`select`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]直连
custom_proxy_group=GooglePlay`select`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]直连

custom_proxy_group=YouTube`select`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]直连
custom_proxy_group=Spotify`select`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]直连
custom_proxy_group=Netflix`select`[]NETFLIX`[]节点选择`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]直连
custom_proxy_group=巴哈姆特`select`[]节点选择`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]🇹🇼 台湾`[]直连
custom_proxy_group=哔哩哔哩`select`[]直连`[]🇭🇰 香港`[]🇲🇴 澳门`[]🇹🇼 台湾`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4
custom_proxy_group=哔哩哔哩港澳台`select`[]直连`[]🇭🇰 香港`[]🇲🇴 澳门`[]🇹🇼 台湾`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4
custom_proxy_group=国内媒体`select`[]直连`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4
custom_proxy_group=国外媒体`select`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]直连

custom_proxy_group=ChatGPT`select`[]节点选择`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]直连
custom_proxy_group=Bing`select`[]节点选择`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]直连

custom_proxy_group=Microsoft`select`[]直连`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4
custom_proxy_group=OneDrive`select`[]直连`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4
custom_proxy_group=Adobe`select`[]直连`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4
custom_proxy_group=Apple`select`[]直连`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4
custom_proxy_group=Telegram`select`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]直连

custom_proxy_group=Epic`select`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]直连
custom_proxy_group=Sony`select`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]直连
custom_proxy_group=Steam`select`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]直连
custom_proxy_group=HoYoGames`select`[]直连`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4

custom_proxy_group=直连`select`[]DIRECT`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4
custom_proxy_group=广告`select`[]REJECT`[]节点选择`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]直连
custom_proxy_group=GFWList`select`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]直连
custom_proxy_group=漏网之鱼`select`[]节点选择`[]🇸🇬 新加坡`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇷🇺 俄罗斯`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`[]直连

custom_proxy_group=🇭🇰 香港`url-test`(港|HK|Hong Kong)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`https://cp.cloudflare.com/generate_204`300,,150
custom_proxy_group=🇹🇼 台湾`url-test`(台|新北|彰化|TW|Taiwan)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡`url-test`(新加坡|坡|狮城|SG|Singapore)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国`url-test`(KR|Korea|KOR|首尔|韩|韓)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇷🇺 俄罗斯`url-test`(RU|Russia|莫斯科|俄|俄罗斯)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇲🇴 澳门`url-test`(MO|Macau|澳门)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=NETFLIX`select`(NF|流媒体|奈飞|解锁|Netflix|NETFLIX|Media)

custom_proxy_group=故障转移`fallback`[]手动选择1`[]手动选择2`[]手动选择3`[]手动选择4`http://www.gstatic.com/generate_204`300,,50

enable_rule_generator=true
overwrite_original_rules=true

#clash_rule_base=https://raw.githubusercontent.com/XiaoMengXinX/Clash_Rules/master/clash_config.yaml
