[custom]
ruleset=本地,[]GEOIP,LAN
ruleset=本地,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=本地,https://raw.githubusercontent.com/XiaoMengXinX/Clash_Rules/master/tailscale.list
ruleset=下载工具,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=广告,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=广告,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=广告,https://ruleset.skk.moe/Clash/ip/reject.txt
ruleset=AppleAI,https://raw.githubusercontent.com/XiaoMengXinX/Clash_Rules/refs/heads/master/AppleAI.list
ruleset=海外AI,https://raw.githubusercontent.com/ArakawaHenri/Clash_Rules/master/clash/rules/google_gemini.list
ruleset=海外AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list
ruleset=Google,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=GoogleCN,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list
ruleset=GoogleCN,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTubeMusic.list
ruleset=TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=Spotify,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Spotify.list
ruleset=海外AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list
ruleset=海外AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.list
ruleset=Bing,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.list
ruleset=Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=OneDrive,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=Apple推送,https://raw.githubusercontent.com/XiaoMengXinX/Clash_Rules/master/apns.list
ruleset=Adobe,https://raw.githubusercontent.com/LM-Firefly/Rules/master/PROXY/Adobe.list
ruleset=WeChat,https://raw.githubusercontent.com/xkww3n/Rules/refs/heads/main/source/wechat.txt
ruleset=Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=Discord,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Discord.list
ruleset=Steam CDN,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Steam_CDN.list
ruleset=Steam CN,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Steam,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=HoYoGames,https://raw.githubusercontent.com/ArakawaHenri/Clash_Rules/master/clash/rules/hoyogames.list
ruleset=巴哈姆特,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=香港银行,https://gitlab.com/KujouYuko/clash_rules/-/raw/master/RuleSet/HKBank.list
ruleset=香港券商,https://gitlab.com/KujouYuko/clash_rules/-/raw/master/RuleSet/HKSecurities.list
ruleset=英国银行,https://raw.githubusercontent.com/ArakawaHenri/Clash_Rules/master/clash/rules/ukbank.list
ruleset=国内站点,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=国内站点,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=国内站点,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=国内站点,[]GEOIP,CN
;ruleset=国内站点,[]GEOSITE,CN
ruleset=国外站点,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=国外站点,[]GEOSITE,geolocation-!cn
ruleset=未归类,[]FINAL

custom_proxy_group=节点选择`select`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择`[]DIRECT
custom_proxy_group=手动选择`select`.*
custom_proxy_group=Google`select`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择`[]通用直连
custom_proxy_group=GoogleCN`select`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择`[]通用直连
custom_proxy_group=FCM`select`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择`[]通用直连
custom_proxy_group=YouTube`select`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择`[]通用直连
custom_proxy_group=TikTok`select`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择`[]通用直连
custom_proxy_group=Spotify`select`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择`[]通用直连
custom_proxy_group=海外AI`select`[]通用代理`[]🇯🇵 日本`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇭🇰 香港`[]手动选择`[]通用直连
custom_proxy_group=AppleAI`select`[]通用代理`[]🇯🇵 日本`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇭🇰 香港`[]手动选择`[]通用直连
custom_proxy_group=巴哈姆特`select`[]🇹🇼 台湾`[]通用代理`[]通用直连`[]手动选择
custom_proxy_group=香港银行`select`[]🇭🇰 香港`[]通用代理`[]通用直连`[]手动选择
custom_proxy_group=香港券商`select`[]通用直连`[]🇭🇰 香港`[]通用代理`[]手动选择
custom_proxy_group=英国银行`select`[]🇬🇧 英国`[]通用代理`[]通用直连`[]手动选择
custom_proxy_group=Microsoft`select`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择`[]通用直连
custom_proxy_group=OneDrive`select`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择`[]通用直连
custom_proxy_group=Apple`select`[]通用直连`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择
custom_proxy_group=APNS`select`[]通用直连`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择
custom_proxy_group=Adobe`select`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择`[]通用直连
custom_proxy_group=WeChat`select`[]通用直连`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择
custom_proxy_group=Telegram`select`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择`[]通用直连
custom_proxy_group=Discord`select`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择`[]通用直连
custom_proxy_group=Bing`select`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择`[]通用直连
custom_proxy_group=Steam`select`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择`[]通用直连
custom_proxy_group=Steam CN`select`[]通用直连`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择
custom_proxy_group=Steam CDN`select`[]通用直连`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择
custom_proxy_group=HoYoGames`select`[]通用直连`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择
custom_proxy_group=国内站点`select`[]通用直连`[]DIRECT`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择
custom_proxy_group=国外站点`select`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择`[]通用直连
custom_proxy_group=广告`select`[]REJECT`[]通用代理`[]手动选择`[]通用直连
custom_proxy_group=本地`select`[]DIRECT`[]通用直连`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择
custom_proxy_group=下载工具`select`[]DIRECT`[]通用直连`[]通用代理`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择
custom_proxy_group=未归类`select`[]通用代理`[]通用直连`[]🇭🇰 香港`[]🇹🇼 台湾`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🇰🇷 韩国`[]🇲🇴 澳门`[]🇬🇧 英国`[]🇩🇪 德国`[]🇧🇷 巴西`[]🇹🇭 泰国`[]🇲🇾 马来西亚`[]🇻🇳 越南`[]🇮🇳 印度`[]🇹🇷 土耳其`[]🇦🇷 阿根廷`[]🇵🇭 菲律宾`[]🇷🇺 俄罗斯`[]🇨🇳 中国`[]手动选择

custom_proxy_group=🇭🇰 香港`select`[]🇭🇰 香港 故障转移`[]🇭🇰 香港 自动测速`(港|HK|Hong Kong)
custom_proxy_group=🇯🇵 日本`select`[]🇯🇵 日本 故障转移`[]🇯🇵 日本 自动测速`(日本|川日|东京|東京|大阪|泉日|埼玉|沪日|深日|日[ ]|日[0-9]|JP|Japan)
custom_proxy_group=🇺🇲 美国`select`[]🇺🇲 美国 故障转移`[]🇺🇲 美国 自动测速`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)
custom_proxy_group=🇹🇼 台湾`select`[]🇹🇼 台湾 故障转移`[]🇹🇼 台湾 自动测速`(台|新北|彰化|TW|Taiwan)
custom_proxy_group=🇸🇬 新加坡`select`[]🇸🇬 新加坡 故障转移`[]🇸🇬 新加坡 自动测速`(新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=🇰🇷 韩国`select`[]🇰🇷 韩国 故障转移`[]🇰🇷 韩国 自动测速`(KR|Korea|KOR|首尔|韩|韓)
custom_proxy_group=🇬🇧 英国`select`[]🇬🇧 英国 故障转移`[]🇬🇧 英国 自动测速`(英国|伦敦|UK|United Kingdom)
custom_proxy_group=🇩🇪 德国`select`[]🇩🇪 德国 故障转移`[]🇩🇪 德国 自动测速`(德国|法兰克福|DE|Germany)
custom_proxy_group=🇧🇷 巴西`select`[]🇧🇷 巴西 故障转移`[]🇧🇷 巴西 自动测速`(巴西|BR|Brazil)
custom_proxy_group=🇹🇭 泰国`select`[]🇹🇭 泰国 故障转移`[]🇹🇭 泰国 自动测速`(泰国|曼谷|TH|Thailand)
custom_proxy_group=🇲🇾 马来西亚`select`[]🇲🇾 马来西亚 故障转移`[]🇲🇾 马来西亚 自动测速`(马来西亚|吉隆坡|MY|Malaysia)
custom_proxy_group=🇻🇳 越南`select`[]🇻🇳 越南 故障转移`[]🇻🇳 越南 自动测速`(越南|VN|Vietnam)
custom_proxy_group=🇮🇳 印度`select`[]🇮🇳 印度 故障转移`[]🇮🇳 印度 自动测速`(印度|孟买|印度尼西亚|IN|India)
custom_proxy_group=🇹🇷 土耳其`select`[]🇹🇷 土耳其 故障转移`[]🇹🇷 土耳其 自动测速`(土耳其|TR|Turkey)
custom_proxy_group=🇦🇷 阿根廷`select`[]🇦🇷 阿根廷 故障转移`[]🇦🇷 阿根廷 自动测速`(阿根廷|AR|Argentina)
custom_proxy_group=🇵🇭 菲律宾`select`[]🇵🇭 菲律宾 故障转移`[]🇵🇭 菲律宾 自动测速`(菲律宾|PH|Philippines)
custom_proxy_group=🇷🇺 俄罗斯`select`[]🇷🇺 俄罗斯 故障转移`[]🇷🇺 俄罗斯 自动测速`(RU|Russia|莫斯科|俄|俄罗斯)
custom_proxy_group=🇲🇴 澳门`select`[]🇲🇴 澳门 故障转移`[]🇲🇴 澳门 自动测速`(MO|Macau|澳门)
custom_proxy_group=🇨🇳 中国`select`[]🇨🇳 中国 故障转移`[]🇨🇳 中国 自动测速`(中国[^台]|回国)

custom_proxy_group=🇭🇰 香港 自动测速`url-test`(港|HK|Hong Kong)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本 自动测速`url-test`(日本|川日|东京|東京|大阪|泉日|埼玉|沪日|深日|日[ ]|日[0-9]|JP|Japan)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国 自动测速`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://cp.cloudflare.com/generate_204`300,,150
custom_proxy_group=🇹🇼 台湾 自动测速`url-test`(台|新北|彰化|TW|Taiwan)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡 自动测速`url-test`(新加坡|坡|狮城|SG|Singapore)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国 自动测速`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇬🇧 英国 自动测速`url-test`(英国|伦敦|UK|United Kingdom)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇩🇪 德国 自动测速`url-test`(德国|法兰克福|DE|Germany)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇧🇷 巴西 自动测速`url-test`(巴西|BR|Brazil)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇹🇭 泰国 自动测速`url-test`(泰国|曼谷|TH|Thailand)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇲🇾 马来西亚 自动测速`url-test`(马来西亚|吉隆坡|MY|Malaysia)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇻🇳 越南 自动测速`url-test`(越南|VN|Vietnam)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇮🇳 印度 自动测速`url-test`(印度|孟买|印度尼西亚|IN|India)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇹🇷 土耳其 自动测速`url-test`(土耳其|TR|Turkey)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇦🇷 阿根廷 自动测速`url-test`(阿根廷|AR|Argentina)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇵🇭 菲律宾 自动测速`url-test`(菲律宾|PH|Philippines)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇷🇺 俄罗斯 自动测速`url-test`(RU|Russia|莫斯科|俄|俄罗斯)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇲🇴 澳门 自动测速`url-test`(MO|Macau|澳门)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇨🇳 中国 自动测速`url-test`(中国[^台]|回国)`http://connect.rom.miui.com/generate_204`300,,50

custom_proxy_group=🇭🇰 香港 故障转移`fallback`(港|HK|Hong Kong)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本 故障转移`fallback`(日本|川日|东京|東京|大阪|泉日|埼玉|沪日|深日|日[ ]|日[0-9]|JP|Japan)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国 故障转移`fallback`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://cp.cloudflare.com/generate_204`300,,150
custom_proxy_group=🇹🇼 台湾 故障转移`fallback`(台|新北|彰化|TW|Taiwan)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡 故障转移`fallback`(新加坡|坡|狮城|SG|Singapore)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国 故障转移`fallback`(KR|Korea|KOR|首尔|韩|韓)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇬🇧 英国 故障转移`fallback`(英国|伦敦|UK|United Kingdom)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇩🇪 德国 故障转移`fallback`(德国|法兰克福|DE|Germany)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇧🇷 巴西 故障转移`fallback`(巴西|BR|Brazil)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇹🇭 泰国 故障转移`fallback`(泰国|曼谷|TH|Thailand)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇲🇾 马来西亚 故障转移`fallback`(马来西亚|吉隆坡|MY|Malaysia)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇻🇳 越南 故障转移`fallback`(越南|VN|Vietnam)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇮🇳 印度 故障转移`fallback`(印度|孟买|印度尼西亚|IN|India)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇹🇷 土耳其 故障转移`fallback`(土耳其|TR|Turkey)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇦🇷 阿根廷 故障转移`fallback`(阿根廷|AR|Argentina)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇵🇭 菲律宾 故障转移`fallback`(菲律宾|PH|Philippines)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇷🇺 俄罗斯 故障转移`fallback`(RU|Russia|莫斯科|俄|俄罗斯)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇲🇴 澳门 故障转移`fallback`(MO|Macau|澳门)`http://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇨🇳 中国 故障转移`fallback`(中国[^台]|回国)`http://connect.rom.miui.com/generate_204`300,,50

custom_proxy_group=通用直连`select`[]DIRECT`[]节点选择`[]手动选择
custom_proxy_group=通用代理`select`[]节点选择`[]DIRECT`[]手动选择

enable_rule_generator=true
overwrite_original_rules=true

clash_rule_base=https://raw.githubusercontent.com/XiaoMengXinX/Clash_Rules/master/stash_config.yaml
